### ISSUE TITLE
Icon.

### ISSUE THREAD

**Issue by octalmage** [octalmage/minum#1]
Need a great icon!

**Comment by octalmage** [comment]
I want the icon to be very minimal, similar to the browser itself, but still look like other browser icons. I had the idea for a circle with a smaller circle in the middle, with flat colors, @therealtaryn though a minus sigh would look good.

**Comment by octalmage** [comment]
Here's a crappy concept made using a crappy online editor, it reminds me of a minimal Chromium icon. 
<img height="100" src="http://40.media.tumblr.com/e11feb789e34a326fdcb08a3289da137/tumblr_noi8uf8Np31qemewjo1_400.png">

![](https://www.chromium.org/_/rsrc/1302286216006/config/customLogo.gif)
(chromium)

I think the concept might work, what do you think @mjchamplin?

**Comment by Therealtaryn** [comment]
The minus symbol was the first thing to come to my mind because of the origins of the word minum obviously, but I wonder how well it would read.  I can make my own crappy concept if you want :p

I dig yours though. I feel like you might want to play with the size of the center dot (bigger?) and I'm not in love with those shades of blue. It may be just because I'm looking at the chromium logo and it's all looking a little drab.

**Comment by octalmage** [comment]
I think I got it!

<img src="http://i.imgur.com/mS50uDm.png" height="100">

This was made on my phone, but I like it. I'll play with it on my computer later.

**Comment by mjchamplin** [comment]
I like this! I may play around with it in illustrator later if that's cool
with you.

**Comment by octalmage** [comment]
Yes please do!

**Comment by octalmage** [comment]
Here's what I came up with: 

![](https://cldup.com/v0jFLrBZ6M.png)

Not sure how I feel about the inner-shadow. It makes it more browser like, but idk. Also not married to the color at all. I'll leave this to you @mjchamplin!

**Comment by mjchamplin** [comment]
Quick gray-scale workups. Riffing on the initial concept, but fine-tuning the proportions and circle-sizing.
![minim](https://cloud.githubusercontent.com/assets/1672613/7684399/506c44e8-fd4b-11e4-8e42-8d7fb3559b3d.png)
Also just playing with the idea of a "refresh" button. I don't love it, but it's a little fun.
![refresh](https://cloud.githubusercontent.com/assets/1672613/7684400/50c1ae6a-fd4b-11e4-843c-e70a05aa685d.png)

**Comment by octalmage** [comment]
Awesome! The wider inner circle is for sure necessary when the icon is smaller.

**Comment by mjchamplin** [comment]
Yeah I like the circle idea. It's sort of the thing with browsers, too. Even Opera is a circle.

**Comment by mjchamplin** [comment]
![icon](https://cloud.githubusercontent.com/assets/1672613/7685979/1dbc50bc-fd58-11e4-95a2-a97aa196594e.png)

**Comment by octalmage** [comment]
Nice! I just uploaded an alpha build, check it out. 

https://github.com/octalmage/minum/releases/tag/v0.0.1-alpha.1

**Comment by mjchamplin** [comment]
Awesome @octalmage -- I'm on a PC right now, so I'll have to check this out tonight. ; )

**Comment by mjchamplin** [comment]
![minum](https://cloud.githubusercontent.com/assets/1672613/7689910/62affb48-fd75-11e4-931d-1b6765d71f4d.png)

**Comment by octalmage** [comment]
Looking good! Could you try a smaller inner circle? In your original concept it looks like it was cut with a laser, I really like that.

**Comment by mjchamplin** [comment]
![icon-2](https://cloud.githubusercontent.com/assets/1672613/7705314/22646e7c-fe09-11e4-80ff-fa726da8b877.png)

**Comment by Therealtaryn** [comment]
I love that color scheme!

**Comment by octalmage** [comment]
I like it too! I think that's the one!

**Comment by mjchamplin** [comment]
![icon-text](https://cloud.githubusercontent.com/assets/1672613/7714681/10fde0ae-fe46-11e4-9a75-ca494f25f01e.png)

**Comment by octalmage** [comment]
As discussed, the size of the inner circle seems off (too big).

![](http://media0.giphy.com/media/nU704Y2jeFOHm/giphy.gif)

**Comment by mjchamplin** [comment]
A subtle difference, but noticeable. This is more like the proportion of the Chrome logo. 

![icon-text-2](https://cloud.githubusercontent.com/assets/1672613/7729967/3fea76a6-fedd-11e4-90d9-3f538e6dcd63.png)

**Comment by octalmage** [comment]
![](http://media0.giphy.com/media/Etgl96VVzkQqQ/giphy.gif)

It's perfect!

**Comment by octalmage** [comment]
Could you send me the icon alone with a transparent background? I want to see it on the dock!

**Comment by mjchamplin** [comment]
Yeah for sure. Here you go: 
![icon](https://cloud.githubusercontent.com/assets/1672613/7736971/66dc2edc-ff0d-11e4-97df-af3d27d0c5bc.png)

Also for now the middle circle is white, but if for some reason it needs to be knocked out we can do that, but I think white will probably be the way to go.

Also I'll be doing this once I have a free minute. http://appicontemplate.com/osx

**Comment by octalmage** [comment]
It looks awesome in the dock! 

![](https://cldup.com/oiQ5p1_Kz5.png)

and yeah the middle circle is good white.

**Comment by octalmage** [comment]
I uploaded the build with the icon, it really does look great!

**Comment by mjchamplin** [comment]
I'm reformatting my Mac right now, but I can't wait to see!

**Comment by mjchamplin** [comment]
Installed. The app looks awesome! Seeing my little icon in my dock is _also_ awesome.

**Comment by octalmage** [comment]
Glad you like it! I'm obsessed, I've been working on the readme all day, and started #6.  

The icon really looks great in the dock, great job man! I guess we can close this issue?

**Comment by mjchamplin** [comment]
Leave it for now. I want to make sure it doesn't need to be optimized or anything.

**Comment by mjchamplin** [comment]
Looks like we're good. We may need to revisit the size / format if we ever submit it to the app store. 

You can close this item. 

![](http://i.giphy.com/jShr8wkP38XTO.gif)

**Comment by octalmage** [comment]
[](http://media0.giphy.com/media/gsqLw0Ok1qvSM/giphy.gif)
(^ that's me)
