### ISSUE TITLE
Background on pages defaulting to gray

### ISSUE THREAD

**Issue by mjchamplin** [octalmage/minum#13]
It appears that page backgrounds which aren't deliberately specified in the CSS might be defaulting to gray for some reason.

Mimum:
![image](https://user-images.githubusercontent.com/1672613/41755826-dfd91fec-759e-11e8-8245-b649b8987dbc.png)

and Chrome: 
![image](https://user-images.githubusercontent.com/1672613/41755862-fde41212-759e-11e8-9412-996d77ad2266.png)

**Comment by mjchamplin** [comment]
You can also use [my photography site](http://photo.mjchamplin.com) as an example. I didn't code it myself so I can't speak for the CSS. I may do a little tinkering and see if I can reproduce it by hand.

**Comment by octalmage** [comment]
Sorry, I closed the wrong issue. This is still open!

**Comment by octalmage** [comment]
This brings up another issue, Layout now: 

![screen shot 2018-06-25 at 10 00 16 pm](https://user-images.githubusercontent.com/142006/41886707-28746802-78c3-11e8-9ed2-4db809ffcec4.png)

The top bar is incorrect, probably because there isn't a background color set and the screenshot it takes is missing a background color. I'll see what I can do about that.

**Comment by octalmage** [comment]
Yup, that's the issue: 
![screen shot 2018-06-25 at 10 11 17 pm](https://user-images.githubusercontent.com/142006/41887052-b3b9035e-78c4-11e8-82ae-f1713df5c523.png)

**Comment by octalmage** [comment]
![image](https://user-images.githubusercontent.com/142006/41887063-bfc3ef38-78c4-11e8-8f24-d36bc19f75bb.png)

**Comment by octalmage** [comment]
All is resolved! v0.1.4 seems to be working better: 

![screen shot 2018-06-25 at 10 38 38 pm](https://user-images.githubusercontent.com/142006/41887927-8f891952-78c8-11e8-9c9c-1b30e0bc114c.png)

![screen shot 2018-06-25 at 10 39 12 pm](https://user-images.githubusercontent.com/142006/41887943-99d02dce-78c8-11e8-9ca8-27b83182e8a6.png)

**Comment by mjchamplin** [comment]
Looking good on my end. The browser looks so slick in fullscreen mode.
